<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TramDungSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $data = [
            ['ten_tram' => 'Bến Xe Miền Đông (Bến Thanh)', 'dia_chi' => 'Hẻm 153 Quốc lộ 13, Khu phố 48, Phường Bình Thạnh, Thủ Đức, TP. Hồ Chí Minh', 'id_phuong_xa' => null, 'id_tuyen_duong' => 4, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 10.814875, 'toa_do_y' => 106.711471, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Ngã Tư Dầu Giây', 'dia_chi' => 'Trần Cao Vân, Dầu Giây, Xã Dầu Giây, Tỉnh Đồng Nai', 'id_phuong_xa' => null, 'id_tuyen_duong' => 4, 'loai_tram' => 'ca_hai', 'thu_tu' => 2, 'toa_do_x' => 10.942482, 'toa_do_y' => 107.140053, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến Xe Liên Tỉnh Đà Lạt', 'dia_chi' => '01 Tô Hiến Thành, Phường 3, TP. Đà Lạt, Lâm Đồng', 'id_phuong_xa' => null, 'id_tuyen_duong' => 4, 'loai_tram' => 'tra', 'thu_tu' => 3, 'toa_do_x' => 11.927500, 'toa_do_y' => 108.444900, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến Xe Trung Tâm Đà Nẵng', 'dia_chi' => 'Đường Cao Sơn Pháo, Hòa Minh, Liên Chiểu, Đà Nẵng', 'id_phuong_xa' => null, 'id_tuyen_duong' => 5, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 16.055010, 'toa_do_y' => 108.173358, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Trạm dừng nghỉ (Hệ thống test)', 'dia_chi' => 'Đường cao tốc Hà Nội - Lào Cai, Xã Xuân Lũng, Tỉnh Phú Thọ', 'id_phuong_xa' => null, 'id_tuyen_duong' => 5, 'loai_tram' => 'ca_hai', 'thu_tu' => 2, 'toa_do_x' => 21.392438, 'toa_do_y' => 105.302228, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe phía Nam Huế', 'dia_chi' => 'An Dương Vương, An Đông, Phường An Cựu, Thành phố Huế', 'id_phuong_xa' => null, 'id_tuyen_duong' => 5, 'loai_tram' => 'tra', 'thu_tu' => 3, 'toa_do_x' => 16.450763, 'toa_do_y' => 107.606019, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Nước Ngầm', 'dia_chi' => '1 Đường Ngọc Hồi, Phường Yên Sở, Quận Hoàng Mai, Hà Nội', 'id_phuong_xa' => null, 'id_tuyen_duong' => 6, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 20.965103, 'toa_do_y' => 105.843176, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe phía Bắc Thanh Hóa', 'dia_chi' => 'Đường Dương Đình Nghệ, Đông Thọ, Hàm Rồng, Tỉnh Thanh Hóa', 'id_phuong_xa' => null, 'id_tuyen_duong' => 6, 'loai_tram' => 'ca_hai', 'thu_tu' => 2, 'toa_do_x' => 19.820239, 'toa_do_y' => 105.773789, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Trạm dừng Sông Sa Lung', 'dia_chi' => 'Phan Xá, Xã Vĩnh Linh, Tỉnh Quảng Trị', 'id_phuong_xa' => null, 'id_tuyen_duong' => 6, 'loai_tram' => 'tra', 'thu_tu' => 3, 'toa_do_x' => 17.044997, 'toa_do_y' => 107.010735, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Miền Đông Mới', 'dia_chi' => 'Xa lộ Hà Nội, Tân Lập, Phường Long Bình, Dĩ An, TP. Hồ Chí Minh', 'id_phuong_xa' => null, 'id_tuyen_duong' => 7, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 10.879596, 'toa_do_y' => 106.815964, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Trung tâm mua vé bến xe Phan Thiết', 'dia_chi' => 'Phan Thiết, Phường Phan Thiết, Tỉnh Bình Thuận', 'id_phuong_xa' => null, 'id_tuyen_duong' => 7, 'loai_tram' => 'ca_hai', 'thu_tu' => 2, 'toa_do_x' => 10.939769, 'toa_do_y' => 108.102867, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Phía Nam Nha Trang', 'dia_chi' => 'Võ Nguyên Giáp, Tây Nha Trang, Diên Khánh, Tỉnh Khánh Hòa', 'id_phuong_xa' => null, 'id_tuyen_duong' => 7, 'loai_tram' => 'tra', 'thu_tu' => 3, 'toa_do_x' => 12.243844, 'toa_do_y' => 109.097981, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Miền Tây', 'dia_chi' => 'Đường Kinh Dương Vương, Phường An Lạc, Quận Bình Tân, TP. HCM', 'id_phuong_xa' => null, 'id_tuyen_duong' => 8, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 10.740127, 'toa_do_y' => 106.619401, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Minh Tâm Quán (Trạm dừng chân)', 'dia_chi' => 'Tân Hiệp, Xã Long Hưng, Tỉnh Tiền Giang', 'id_phuong_xa' => null, 'id_tuyen_duong' => 8, 'loai_tram' => 'ca_hai', 'thu_tu' => 2, 'toa_do_x' => 10.429504, 'toa_do_y' => 106.316814, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Trung tâm tp. Cần Thơ', 'dia_chi' => 'Đường Trần Hoàng Na, Phường Cái Răng, Thành phố Cần Thơ', 'id_phuong_xa' => null, 'id_tuyen_duong' => 8, 'loai_tram' => 'tra', 'thu_tu' => 3, 'toa_do_x' => 10.005344, 'toa_do_y' => 105.771312, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Nước Ngầm', 'dia_chi' => 'Số 1 Ngọc Hồi, Hoàng Liệt, Hoàng Mai', 'id_phuong_xa' => null, 'id_tuyen_duong' => 10, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 20.963400, 'toa_do_y' => 105.842700, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Cầu Rào', 'dia_chi' => 'Số 1 Thiên Lôi, Đằng Giang, Ngô Quyền', 'id_phuong_xa' => null, 'id_tuyen_duong' => 10, 'loai_tram' => 'tra', 'thu_tu' => 2, 'toa_do_x' => 20.835900, 'toa_do_y' => 106.697500, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Mỹ Đình', 'dia_chi' => '20 Đường Phạm Hùng, Phường Mỹ Đình, Nam Từ Liêm, Hà Nội', 'id_phuong_xa' => null, 'id_tuyen_duong' => 11, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 21.028405, 'toa_do_y' => 105.778314, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Trạm dừng Duy Tân', 'dia_chi' => 'Duy Tân, Phường Quảng Phú, Thành phố Đà Nẵng', 'id_phuong_xa' => null, 'id_tuyen_duong' => 11, 'loai_tram' => 'ca_hai', 'thu_tu' => 2, 'toa_do_x' => 15.580249, 'toa_do_y' => 108.513653, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Phường Phú Thọ (Điểm tập kết)', 'dia_chi' => 'Phường Phú Thọ, Thành phố Hồ Chí Minh', 'id_phuong_xa' => null, 'id_tuyen_duong' => 11, 'loai_tram' => 'tra', 'thu_tu' => 3, 'toa_do_x' => 10.765870, 'toa_do_y' => 106.654623, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến Xe Trung Tâm Đà Nẵng', 'dia_chi' => 'Đường Nguyễn Quyền, Hòa An, An Khê, Đà Nẵng', 'id_phuong_xa' => null, 'id_tuyen_duong' => 15, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 16.055010, 'toa_do_y' => 108.173358, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Liên tỉnh Phú Yên', 'dia_chi' => 'Nguyễn Tất Thành, Tuy Hòa, Phú Yên', 'id_phuong_xa' => null, 'id_tuyen_duong' => 15, 'loai_tram' => 'ca_hai', 'thu_tu' => 2, 'toa_do_x' => 13.092588, 'toa_do_y' => 109.294210, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến Xe Bắc Nha Trang', 'dia_chi' => '01 Đường 2 Tháng 4, Vĩnh Hòa, Nha Trang, Khánh Hòa', 'id_phuong_xa' => null, 'id_tuyen_duong' => 15, 'loai_tram' => 'tra', 'thu_tu' => 3, 'toa_do_x' => 12.288685, 'toa_do_y' => 109.190585, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến Xe Trung Tâm Đà Nẵng', 'dia_chi' => 'Đường Nguyễn Quyền, Hòa An, Cẩm Lệ, Đà Nẵng', 'id_phuong_xa' => null, 'id_tuyen_duong' => 17, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 16.055010, 'toa_do_y' => 108.173358, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Kon Tum', 'dia_chi' => '281 Phan Đình Phùng, Phường Quang Trung, TP. Kon Tum', 'id_phuong_xa' => null, 'id_tuyen_duong' => 17, 'loai_tram' => 'tra', 'thu_tu' => 2, 'toa_do_x' => 14.349753, 'toa_do_y' => 108.001242, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe phía Nam (Huế)', 'dia_chi' => 'An Dương Vương, An Đông, Phường An Cựu, Thành phố Huế', 'id_phuong_xa' => null, 'id_tuyen_duong' => 18, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 16.450763, 'toa_do_y' => 107.606019, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Hội An', 'dia_chi' => '02 Nguyễn Tất Thành, Tân An, Hội An, Quảng Nam', 'id_phuong_xa' => null, 'id_tuyen_duong' => 18, 'loai_tram' => 'tra', 'thu_tu' => 2, 'toa_do_x' => 15.885600, 'toa_do_y' => 108.327400, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe phía Nam (Huế)', 'dia_chi' => 'An Dương Vương, An Đông, Phường An Cựu, Thành phố Huế', 'id_phuong_xa' => null, 'id_tuyen_duong' => 19, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 16.450763, 'toa_do_y' => 107.606019, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Nam Lý', 'dia_chi' => 'Đường Tố Hữu, Phường Đồng Hới, Tỉnh Quảng Bình', 'id_phuong_xa' => null, 'id_tuyen_duong' => 19, 'loai_tram' => 'ca_hai', 'thu_tu' => 2, 'toa_do_x' => 17.468155, 'toa_do_y' => 106.604314, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến Xe Bắc Nha Trang', 'dia_chi' => 'Đường 2 Tháng 4, Phường Vĩnh Hòa, Nha Trang, Khánh Hòa', 'id_phuong_xa' => null, 'id_tuyen_duong' => 19, 'loai_tram' => 'tra', 'thu_tu' => 3, 'toa_do_x' => 12.288685, 'toa_do_y' => 109.190585, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Nam Lý', 'dia_chi' => 'Đường Tố Hữu, Phường Đồng Hới, Tỉnh Quảng Bình', 'id_phuong_xa' => null, 'id_tuyen_duong' => 20, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 17.468155, 'toa_do_y' => 106.604314, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe KonTum', 'dia_chi' => 'Đường Phan Đình Phùng, Trung Tín, Phường Kon Tum', 'id_phuong_xa' => null, 'id_tuyen_duong' => 20, 'loai_tram' => 'ca_hai', 'thu_tu' => 2, 'toa_do_x' => 14.367456, 'toa_do_y' => 107.994140, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Liên tỉnh Phú Yên (Đắk Lắk)', 'dia_chi' => 'Đại lộ Nguyễn Tất Thành, Phú Vang, Phường Tuy Hòa, Đắk Lắk', 'id_phuong_xa' => null, 'id_tuyen_duong' => 20, 'loai_tram' => 'tra', 'thu_tu' => 3, 'toa_do_x' => 13.092588, 'toa_do_y' => 109.294210, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Nước Ngầm', 'dia_chi' => 'Số 1 Ngọc Hồi, Hoàng Liệt, Hoàng Mai', 'id_phuong_xa' => null, 'id_tuyen_duong' => 21, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 20.963400, 'toa_do_y' => 105.842700, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Cầu Rào', 'dia_chi' => 'Số 1 Thiên Lôi, Đằng Giang, Ngô Quyền', 'id_phuong_xa' => null, 'id_tuyen_duong' => 21, 'loai_tram' => 'tra', 'thu_tu' => 2, 'toa_do_x' => 20.835900, 'toa_do_y' => 106.697500, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Mỹ Đình', 'dia_chi' => '20 Đường Phạm Hùng, Phường Mỹ Đình, Nam Từ Liêm, Hà Nội', 'id_phuong_xa' => null, 'id_tuyen_duong' => 22, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 21.028405, 'toa_do_y' => 105.778314, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Trạm dừng Duy Tân', 'dia_chi' => 'Duy Tân, Phường Quảng Phú, Thành phố Đà Nẵng', 'id_phuong_xa' => null, 'id_tuyen_duong' => 22, 'loai_tram' => 'ca_hai', 'thu_tu' => 2, 'toa_do_x' => 15.580249, 'toa_do_y' => 108.513653, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Phường Phú Thọ (Điểm tập kết)', 'dia_chi' => 'Phường Phú Thọ, Thành phố Hồ Chí Minh', 'id_phuong_xa' => null, 'id_tuyen_duong' => 22, 'loai_tram' => 'tra', 'thu_tu' => 3, 'toa_do_x' => 10.765870, 'toa_do_y' => 106.654623, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Miền Đông Mới', 'dia_chi' => 'Xa lộ Hà Nội, Hiệp Thắng, Phường Đông Hòa, Thành phố Hồ Chí Minh', 'id_phuong_xa' => null, 'id_tuyen_duong' => 23, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 10.879596, 'toa_do_y' => 106.815964, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Đồng Xoài', 'dia_chi' => 'Phường Tân Đồng, Thành phố Đồng Xoài, Bình Phước', 'id_phuong_xa' => null, 'id_tuyen_duong' => 23, 'loai_tram' => 'ca_hai', 'thu_tu' => 2, 'toa_do_x' => 11.530300, 'toa_do_y' => 106.903800, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Phước Long', 'dia_chi' => 'Đường Nguyễn Xí, Phường Phước Long, Bình Phước', 'id_phuong_xa' => null, 'id_tuyen_duong' => 23, 'loai_tram' => 'tra', 'thu_tu' => 3, 'toa_do_x' => 11.840768, 'toa_do_y' => 106.993245, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Miền Tây', 'dia_chi' => 'Kinh Dương Vương, Phường An Lac, Bình Tân, TP. Hồ Chí Minh', 'id_phuong_xa' => null, 'id_tuyen_duong' => 24, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 10.740127, 'toa_do_y' => 106.619401, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Bến Tre', 'dia_chi' => 'Quốc lộ 60, Phường Sơn Đông, Tỉnh Bến Tre', 'id_phuong_xa' => null, 'id_tuyen_duong' => 24, 'loai_tram' => 'tra', 'thu_tu' => 2, 'toa_do_x' => 10.266472, 'toa_do_y' => 106.359759, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Miền Đông Mới', 'dia_chi' => 'Xa lộ Hà Nội, Tân Lập, Phường Long Bình, TP. Thủ Đức, TP. Hồ Chí Minh', 'id_phuong_xa' => null, 'id_tuyen_duong' => 25, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 10.879596, 'toa_do_y' => 106.815964, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Nội Thành (Tuy Hòa)', 'dia_chi' => 'Đường Nguyễn Trãi, Tuy Hòa, Tỉnh Phú Yên', 'id_phuong_xa' => null, 'id_tuyen_duong' => 25, 'loai_tram' => 'tra', 'thu_tu' => 2, 'toa_do_x' => 13.087705, 'toa_do_y' => 109.306893, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Miền Đông Mới', 'dia_chi' => 'Xa lộ Hà Nội, Tân Lập, Phường Long Bình, TP. Thủ Đức, TP. Hồ Chí Minh', 'id_phuong_xa' => null, 'id_tuyen_duong' => 26, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 10.879596, 'toa_do_y' => 106.815964, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe KonTum', 'dia_chi' => 'Đường Phan Đình Phùng, Phường Kon Tum, Tỉnh Kon Tum', 'id_phuong_xa' => null, 'id_tuyen_duong' => 26, 'loai_tram' => 'tra', 'thu_tu' => 2, 'toa_do_x' => 14.367456, 'toa_do_y' => 107.994140, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Miền Đông Mới', 'dia_chi' => 'Xa lộ Hà Nội, Phường Long Bình, TP. Thủ Đức, TP. Hồ Chí Minh', 'id_phuong_xa' => null, 'id_tuyen_duong' => 27, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 10.879596, 'toa_do_y' => 106.815964, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến Xe Trung Tâm Đà Nẵng', 'dia_chi' => 'Đường Cao Sơn Pháo, Hòa Minh, Liên Chiểu, Đà Nẵng', 'id_phuong_xa' => null, 'id_tuyen_duong' => 27, 'loai_tram' => 'tra', 'thu_tu' => 2, 'toa_do_x' => 16.055010, 'toa_do_y' => 108.173358, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Miền Tây', 'dia_chi' => 'Đường Kinh Dương Vương, Phường An Lạc, Quận Bình Tân, TP. Hồ Chí Minh', 'id_phuong_xa' => null, 'id_tuyen_duong' => 28, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 10.740127, 'toa_do_y' => 106.619401, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Trung tâm tp.Cần Thơ', 'dia_chi' => 'Trần Hoàng Na, Phường Cái Răng, Thành phố Cần Thơ', 'id_phuong_xa' => null, 'id_tuyen_duong' => 28, 'loai_tram' => 'ca_hai', 'thu_tu' => 2, 'toa_do_x' => 10.005344, 'toa_do_y' => 105.771312, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Trạm dừng chân Minh Khải', 'dia_chi' => 'Quốc lộ 1, Xã Nhu Gia, Mỹ Xuyên, Tỉnh Sóc Trăng', 'id_phuong_xa' => null, 'id_tuyen_duong' => 28, 'loai_tram' => 'ca_hai', 'thu_tu' => 3, 'toa_do_x' => 9.512648, 'toa_do_y' => 105.873061, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Cà Mau', 'dia_chi' => 'Lý Thường Kiệt, Phường Tân Thành, Tỉnh Cà Mau', 'id_phuong_xa' => null, 'id_tuyen_duong' => 28, 'loai_tram' => 'tra', 'thu_tu' => 4, 'toa_do_x' => 9.175770, 'toa_do_y' => 105.170944, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Miền Tây', 'dia_chi' => 'Đường Kinh Dương Vương, Phường An Lạc, Quận Bình Tân, TP. Hồ Chí Minh', 'id_phuong_xa' => null, 'id_tuyen_duong' => 28, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 10.740127, 'toa_do_y' => 106.619401, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Trung tâm tp.Cần Thơ', 'dia_chi' => 'Đường Trần Hoàng Na, Phường Cái Răng, Thành phố Cần Thơ', 'id_phuong_xa' => null, 'id_tuyen_duong' => 28, 'loai_tram' => 'tra', 'thu_tu' => 2, 'toa_do_x' => 10.005344, 'toa_do_y' => 105.771312, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến Xe Trung Tâm Đà Nẵng', 'dia_chi' => 'Đường Nguyễn Quyền, Hòa An, An Khê, Đà Nẵng', 'id_phuong_xa' => null, 'id_tuyen_duong' => 16, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 16.055010, 'toa_do_y' => 108.173358, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe khách Quy Nhơn', 'dia_chi' => '71 Tây Sơn, Ghềnh Ráng, Quy Nhơn, Bình Định', 'id_phuong_xa' => null, 'id_tuyen_duong' => 16, 'loai_tram' => 'ca_hai', 'thu_tu' => 2, 'toa_do_x' => 13.753340, 'toa_do_y' => 109.208907, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Liên tỉnh Phú Yên', 'dia_chi' => 'Nguyễn Tất Thành, Phường Tuy Hòa, Tỉnh Phú Yên', 'id_phuong_xa' => null, 'id_tuyen_duong' => 16, 'loai_tram' => 'tra', 'thu_tu' => 3, 'toa_do_x' => 13.092588, 'toa_do_y' => 109.294210, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe khách Quy Nhơn', 'dia_chi' => 'Quốc lộ 1D, Ghềnh Ráng, Thành phố Quy Nhơn, Bình Định', 'id_phuong_xa' => null, 'id_tuyen_duong' => 9, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 13.753340, 'toa_do_y' => 109.208907, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Thị xã An Khê', 'dia_chi' => 'Phường An Khê, Thị xã An Khê, Tỉnh Gia Lai', 'id_phuong_xa' => null, 'id_tuyen_duong' => 9, 'loai_tram' => 'ca_hai', 'thu_tu' => 2, 'toa_do_x' => 14.022384, 'toa_do_y' => 108.695029, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Quảng trường Đại Đoàn Kết', 'dia_chi' => 'Trần Hưng Đạo, Phường Pleiku, Thành phố Pleiku, Gia Lai', 'id_phuong_xa' => null, 'id_tuyen_duong' => 9, 'loai_tram' => 'tra', 'thu_tu' => 3, 'toa_do_x' => 13.982935, 'toa_do_y' => 108.005989, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến Xe Trung Tâm Đà Nẵng', 'dia_chi' => 'Đường Nguyễn Quyền, Hòa An, Phường An Khê, Thành phố Đà Nẵng', 'id_phuong_xa' => null, 'id_tuyen_duong' => 14, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 16.055010, 'toa_do_y' => 108.173358, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến Xe Quảng Ngãi', 'dia_chi' => 'Đinh Tiên Hoàng, Nghĩa Chánh, Quảng Ngãi, Tỉnh Quảng Ngãi', 'id_phuong_xa' => null, 'id_tuyen_duong' => 14, 'loai_tram' => 'ca_hai', 'thu_tu' => 2, 'toa_do_x' => 15.107484, 'toa_do_y' => 108.819131, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe khách Quy Nhơn', 'dia_chi' => 'Quốc lộ 1D, Ghềnh Ráng, Phường Quy Nhơn Nam, Quy Nhơn', 'id_phuong_xa' => null, 'id_tuyen_duong' => 14, 'loai_tram' => 'tra', 'thu_tu' => 3, 'toa_do_x' => 13.753340, 'toa_do_y' => 109.208907, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến Xe Trung Tâm Đà Nẵng', 'dia_chi' => 'Đường Nguyễn Văn Tạo, Hòa An, An Khê, Đà Nẵng', 'id_phuong_xa' => null, 'id_tuyen_duong' => 12, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 16.055010, 'toa_do_y' => 105.778314, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe phía Nam Nha Trang', 'dia_chi' => '23 Tháng 10, Tây Nha Trang, Khánh Hòa', 'id_phuong_xa' => null, 'id_tuyen_duong' => 12, 'loai_tram' => 'ca_hai', 'thu_tu' => 2, 'toa_do_x' => 12.258395, 'toa_do_y' => 109.134856, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Phan Thiết', 'dia_chi' => 'Trung tâm mua vé bến xe, TP. Phan Thiết, Bình Thuận', 'id_phuong_xa' => null, 'id_tuyen_duong' => 12, 'loai_tram' => 'ca_hai', 'thu_tu' => 3, 'toa_do_x' => 10.939769, 'toa_do_y' => 108.102867, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Vũng Tàu', 'dia_chi' => '192 Nam Kỳ Khởi Nghĩa, Vũng Tàu', 'id_phuong_xa' => null, 'id_tuyen_duong' => 12, 'loai_tram' => 'tra', 'thu_tu' => 4, 'toa_do_x' => 10.350447, 'toa_do_y' => 107.087048, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến Xe Trung Tâm Đà Nẵng', 'dia_chi' => 'Đường Nguyễn Quyền, Hòa An, Phường An Khê, Thành phố Đà Nẵng', 'id_phuong_xa' => null, 'id_tuyen_duong' => 13, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 16.055010, 'toa_do_y' => 108.173358, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Tam Kỳ - 1 Phan Bội Châu', 'dia_chi' => 'Quốc lộ 1, Phường Bàn Thạch, Thành phố Tam Kỳ', 'id_phuong_xa' => null, 'id_tuyen_duong' => 13, 'loai_tram' => 'ca_hai', 'thu_tu' => 2, 'toa_do_x' => 15.586615, 'toa_do_y' => 108.465371, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến Xe Quảng Ngãi', 'dia_chi' => 'Đinh Tiên Hoàng, Nghĩa Chánh, Phường Cẩm Thành, Tỉnh Quảng Ngãi', 'id_phuong_xa' => null, 'id_tuyen_duong' => 13, 'loai_tram' => 'tra', 'thu_tu' => 3, 'toa_do_x' => 15.107484, 'toa_do_y' => 108.819131, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Mỹ Đình', 'dia_chi' => '20 Đường Phạm Hùng, Phường Mỹ Đình, Nam Từ Liêm, Hà Nội', 'id_phuong_xa' => null, 'id_tuyen_duong' => 2, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 21.028405, 'toa_do_y' => 105.778314, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Trạm dừng Duy Tân', 'dia_chi' => 'Duy Tân, Phường Quảng Phú, Thành phố Đà Nẵng', 'id_phuong_xa' => null, 'id_tuyen_duong' => 2, 'loai_tram' => 'ca_hai', 'thu_tu' => 2, 'toa_do_x' => 15.580249, 'toa_do_y' => 108.513653, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Phường Phú Thọ (Điểm tập kết)', 'dia_chi' => 'Phường Phú Thọ, Thành phố Hồ Chí Minh', 'id_phuong_xa' => null, 'id_tuyen_duong' => 2, 'loai_tram' => 'tra', 'thu_tu' => 3, 'toa_do_x' => 10.765870, 'toa_do_y' => 106.654623, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Nước Ngầm', 'dia_chi' => 'Số 1 Ngọc Hồi, Hoàng Liệt, Hoàng Mai', 'id_phuong_xa' => null, 'id_tuyen_duong' => 1, 'loai_tram' => 'don', 'thu_tu' => 1, 'toa_do_x' => 20.963400, 'toa_do_y' => 105.842700, 'tinh_trang' => 'hoat_dong'],
            ['ten_tram' => 'Bến xe Cầu Rào', 'dia_chi' => 'Số 1 Thiên Lôi, Đằng Giang, Ngô Quyền', 'id_phuong_xa' => null, 'id_tuyen_duong' => 1, 'loai_tram' => 'tra', 'thu_tu' => 2, 'toa_do_x' => 20.835900, 'toa_do_y' => 106.697500, 'tinh_trang' => 'hoat_dong'],

        ];

        // Tự động gắn thêm created_at và updated_at cho từng dòng
        $data = array_map(function ($item) use ($now) {
            $item['created_at'] = $now;
            $item['updated_at'] = $now;
            return $item;
        }, $data);

        // Chèn vào database bằng DB::table để tối ưu hiệu suất (Insert hàng loạt)
        DB::table('tram_dungs')->insert($data);
    }
}
