<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TuyenDuongSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $routes = [
            [
                'ma_nha_xe' => 'NX001',
                'ten_tuyen_duong' => 'Hà Nội - Hải Phòng (Sửa)',
                'diem_bat_dau' => 'Hà Nội',
                'diem_ket_thuc' => 'Hải Phòng',
                'quang_duong' => 120.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5]',
                'gio_khoi_hanh' => '06:00:00',
                'gio_ket_thuc' => '08:00:00',
                'gio_du_kien' => 2,
                'gia_ve_co_ban' => 16000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến cao tốc chạy nhanh',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX001',
                'ten_tuyen_duong' => 'Hà Nội - Hồ Chí Minh',
                'diem_bat_dau' => 'Hà Nội',
                'diem_ket_thuc' => 'TP. Hồ Chí Minh',
                'quang_duong' => 1750.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,5,6,4]',
                'gio_khoi_hanh' => '08:00:00',
                'gio_ket_thuc' => '20:00:00',
                'gio_du_kien' => 36,
                'gia_ve_co_ban' => 940000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến đường dài xuyên Việt qua các trạm dừng lớn',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX002',
                'ten_tuyen_duong' => 'TP. Hồ Chí Minh - Đà Lạt',
                'diem_bat_dau' => 'TP. Hồ Chí Minh',
                'diem_ket_thuc' => 'Đà Lạt',
                'quang_duong' => 307.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '07:00:00',
                'gio_ket_thuc' => '14:00:00',
                'gio_du_kien' => 7,
                'gia_ve_co_ban' => 250000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến đường đi qua Cao tốc Long Thành - Dầu Giây và Quốc lộ 20',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX002',
                'ten_tuyen_duong' => 'Đà Nẵng - Huế',
                'diem_bat_dau' => 'Đà Nẵng',
                'diem_ket_thuc' => 'Huế',
                'quang_duong' => 100.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '08:00:00',
                'gio_ket_thuc' => '10:30:00',
                'gio_du_kien' => 3,
                'gia_ve_co_ban' => 120000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến đường Đà Nẵng - Huế đi qua trạm dừng nghỉ thực tế',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX002',
                'ten_tuyen_duong' => 'Hà Nội - Quảng Trị',
                'diem_bat_dau' => 'Hà Nội',
                'diem_ket_thuc' => 'Quảng Trị',
                'quang_duong' => 600.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '05:00:00',
                'gio_ket_thuc' => '17:00:00',
                'gio_du_kien' => 12,
                'gia_ve_co_ban' => 350000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến đường dài xuyên nhiều tỉnh miền Trung, chạy ban ngày',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX002',
                'ten_tuyen_duong' => 'TP. Hồ Chí Minh - Nha Trang',
                'diem_bat_dau' => 'TP. Hồ Chí Minh',
                'diem_ket_thuc' => 'Nha Trang',
                'quang_duong' => 435.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '06:00:00',
                'gio_ket_thuc' => '15:00:00',
                'gio_du_kien' => 9,
                'gia_ve_co_ban' => 320000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến đường ven biển đi qua Phan Thiết và Nha Trang, xe giường nằm chất lượng cao',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX002',
                'ten_tuyen_duong' => 'TP. Hồ Chí Minh - Cần Thơ',
                'diem_bat_dau' => 'TP. Hồ Chí Minh',
                'diem_ket_thuc' => 'Cần Thơ',
                'quang_duong' => 165.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '08:00:00',
                'gio_ket_thuc' => '11:30:00',
                'gio_du_kien' => 4,
                'gia_ve_co_ban' => 180000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến xe miền Tây chất lượng cao, đi qua cao tốc Trung Lương',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX002',
                'ten_tuyen_duong' => 'Quy Nhơn - Pleiku',
                'diem_bat_dau' => 'Quy Nhơn',
                'diem_ket_thuc' => 'Pleiku',
                'quang_duong' => 165.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '08:00:00',
                'gio_ket_thuc' => '12:00:00',
                'gio_du_kien' => 4,
                'gia_ve_co_ban' => 160000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến xe Limousine Quy Nhơn - Pleiku, trả khách tại Quảng trường trung tâm',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX001',
                'ten_tuyen_duong' => 'Hà Nội - Hải Phòng',
                'diem_bat_dau' => 'Hà Nội',
                'diem_ket_thuc' => 'Hải Phòng',
                'quang_duong' => 120.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '06:00:00',
                'gio_ket_thuc' => '08:00:00',
                'gio_du_kien' => 2,
                'gia_ve_co_ban' => 150000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến cao tốc chạy nhanh',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX001',
                'ten_tuyen_duong' => 'Hà Nội - Lào Cai (Sapa) - Xuyên Việt',
                'diem_bat_dau' => 'Hà Nội',
                'diem_ket_thuc' => 'TP. Hồ Chí Minh',
                'quang_duong' => 1750.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '08:00:00',
                'gio_ket_thuc' => '20:00:00',
                'gio_du_kien' => 36,
                'gia_ve_co_ban' => 950000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến đường dài xuyên Việt qua các trạm dừng lớn',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX001',
                'ten_tuyen_duong' => 'Đà Nẵng - Vũng Tàu',
                'diem_bat_dau' => 'Đà Nẵng',
                'diem_ket_thuc' => 'Vũng Tàu',
                'quang_duong' => 900.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5]',
                'gio_khoi_hanh' => '14:00:00',
                'gio_ket_thuc' => '23:59:00',
                'gio_du_kien' => 17,
                'gia_ve_co_ban' => 550000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Lộ trình dọc Quốc lộ 1A qua các trạm dừng Miền Trung và Nam Trung Bộ',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX001',
                'ten_tuyen_duong' => 'Đà Nẵng - Quảng Ngãi',
                'diem_bat_dau' => 'Đà Nẵng',
                'diem_ket_thuc' => 'Quảng Ngãi',
                'quang_duong' => 150.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '08:00:00',
                'gio_ket_thuc' => '11:00:00',
                'gio_du_kien' => 3,
                'gia_ve_co_ban' => 120000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến đường ven biển Miền Trung qua Quốc lộ 1A',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX001',
                'ten_tuyen_duong' => 'Đà Nẵng - Quảng Ngãi - Quy Nhơn',
                'diem_bat_dau' => 'Đà Nẵng',
                'diem_ket_thuc' => 'Quy Nhơn',
                'quang_duong' => 320.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '07:00:00',
                'gio_ket_thuc' => '13:00:00',
                'gio_du_kien' => 6,
                'gia_ve_co_ban' => 250000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến đường ven biển miền Trung qua các bến xe trung tâm',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX001',
                'ten_tuyen_duong' => 'Đà Nẵng - Nha Trang',
                'diem_bat_dau' => 'Đà Nẵng',
                'diem_ket_thuc' => 'Nha Trang',
                'quang_duong' => 530.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '06:00:00',
                'gio_ket_thuc' => '17:00:00',
                'gio_du_kien' => 11,
                'gia_ve_co_ban' => 350000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến đường dọc quốc lộ 1A qua các tỉnh miền Trung và Nam Trung Bộ',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX001',
                'ten_tuyen_duong' => 'Đà Nẵng - Phú Yên',
                'diem_bat_dau' => 'Đà Nẵng',
                'diem_ket_thuc' => 'Phú Yên',
                'quang_duong' => 410.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '07:00:00',
                'gio_ket_thuc' => '15:00:00',
                'gio_du_kien' => 8,
                'gia_ve_co_ban' => 280000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến đường ven biển đi qua đèo Cù Mông',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX001',
                'ten_tuyen_duong' => 'Đà Nẵng - Kon Tum',
                'diem_bat_dau' => 'Đà Nẵng',
                'diem_ket_thuc' => 'Kon Tum',
                'quang_duong' => 290.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '08:00:00',
                'gio_ket_thuc' => '14:00:00',
                'gio_du_kien' => 6,
                'gia_ve_co_ban' => 200000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến đường qua Quốc lộ 14E và Quốc lộ 14, kết nối miền Trung với Bắc Tây Nguyên',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX001',
                'ten_tuyen_duong' => 'Huế - Hội An (Tuyến nhanh)',
                'diem_bat_dau' => 'Huế',
                'diem_ket_thuc' => 'Hội An',
                'quang_duong' => 105.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '08:00:00',
                'gio_ket_thuc' => '10:30:00',
                'gio_du_kien' => 3,
                'gia_ve_co_ban' => 120000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến chạy thẳng từ Bến xe phía Nam Huế đến Bến xe Hội An',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX001',
                'ten_tuyen_duong' => 'Quảng Trị - Quảng Bình',
                'diem_bat_dau' => 'Quảng Trị',
                'diem_ket_thuc' => 'Quảng Bình',
                'quang_duong' => 100.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '07:00:00',
                'gio_ket_thuc' => '09:00:00',
                'gio_du_kien' => 2,
                'gia_ve_co_ban' => 100000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến đường kết nối các tỉnh Bắc Trung Bộ theo dữ liệu tọa độ hệ thống',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX001',
                'ten_tuyen_duong' => 'Quảng Bình - Đắk Lắk',
                'diem_bat_dau' => 'Quảng Bình',
                'diem_ket_thuc' => 'Đắk Lắk',
                'quang_duong' => 580.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '05:00:00',
                'gio_ket_thuc' => '18:00:00',
                'gio_du_kien' => 13,
                'gia_ve_co_ban' => 380000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến chạy trong ngày để tránh lỗi validation',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX001',
                'ten_tuyen_duong' => 'Hà Nội - Hải Phòng',
                'diem_bat_dau' => 'Hà Nội',
                'diem_ket_thuc' => 'Hải Phòng',
                'quang_duong' => 120.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '06:00:00',
                'gio_ket_thuc' => '08:00:00',
                'gio_du_kien' => 2,
                'gia_ve_co_ban' => 150000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến cao tốc chạy nhanh',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX001',
                'ten_tuyen_duong' => 'Hà Nội - Lào Cai (Sapa) - Xuyên Việt',
                'diem_bat_dau' => 'Hà Nội',
                'diem_ket_thuc' => 'TP. Hồ Chí Minh',
                'quang_duong' => 1750.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '08:00:00',
                'gio_ket_thuc' => '20:00:00',
                'gio_du_kien' => 36,
                'gia_ve_co_ban' => 950000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến đường dài xuyên Việt qua các trạm dừng lớn',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX003',
                'ten_tuyen_duong' => 'Hồ Chí Minh - Bình Phước (3 điểm dừng)',
                'diem_bat_dau' => 'Hồ Chí Minh',
                'diem_ket_thuc' => 'Bình Phước',
                'quang_duong' => 135.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '07:00:00',
                'gio_ket_thuc' => '10:30:00',
                'gio_du_kien' => 4,
                'gia_ve_co_ban' => 180000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Xe khách giường nằm đi Phước Long, dừng đón trả tại Đồng Xoài',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX003',
                'ten_tuyen_duong' => 'TP. Hồ Chí Minh - Bến Tre',
                'diem_bat_dau' => 'Hồ Chí Minh',
                'diem_ket_thuc' => 'Bến Tre',
                'quang_duong' => 85.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '07:00:00',
                'gio_ket_thuc' => '09:30:00',
                'gio_du_kien' => 3,
                'gia_ve_co_ban' => 110000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến đi qua cao tốc Trung Lương và Quốc lộ 60',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX003',
                'ten_tuyen_duong' => 'TP. Hồ Chí Minh - Phú Yên',
                'diem_bat_dau' => 'Hồ Chí Minh',
                'diem_ket_thuc' => 'Phú Yên',
                'quang_duong' => 550.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '06:00:00',
                'gio_ket_thuc' => '18:00:00',
                'gio_du_kien' => 12,
                'gia_ve_co_ban' => 320000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến đường dọc Quốc lộ 1A từ Bến xe Miền Đông mới đi Tuy Hòa',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX003',
                'ten_tuyen_duong' => 'TP. Hồ Chí Minh - Kon Tum',
                'diem_bat_dau' => 'Hồ Chí Minh',
                'diem_ket_thuc' => 'Kon Tum',
                'quang_duong' => 600.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '07:00:00',
                'gio_ket_thuc' => '21:00:00',
                'gio_du_kien' => 14,
                'gia_ve_co_ban' => 380000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến đường Hồ Chí Minh qua các tỉnh Tây Nguyên đến Kon Tum',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX003',
                'ten_tuyen_duong' => 'TP. Hồ Chí Minh - Đà Nẵng',
                'diem_bat_dau' => 'Hồ Chí Minh',
                'diem_ket_thuc' => 'Đà Nẵng',
                'quang_duong' => 930.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '04:00:00',
                'gio_ket_thuc' => '23:50:00',
                'gio_du_kien' => 20,
                'gia_ve_co_ban' => 450000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến đường dọc Quốc lộ 1A xuyên miền Trung từ Bến xe Miền Đông mới',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX003',
                'ten_tuyen_duong' => 'TP. Hồ Chí Minh - Cà Mau',
                'diem_bat_dau' => 'Hồ Chí Minh',
                'diem_ket_thuc' => 'Cà Mau',
                'quang_duong' => 310.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '08:00:00',
                'gio_ket_thuc' => '16:00:00',
                'gio_du_kien' => 8,
                'gia_ve_co_ban' => 220000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến đường đi qua các tỉnh Miền Tây dọc theo Quốc lộ 1A',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ma_nha_xe' => 'NX003',
                'ten_tuyen_duong' => 'TP. Hồ Chí Minh - Cần Thơ',
                'diem_bat_dau' => 'Hồ Chí Minh',
                'diem_ket_thuc' => 'Cần Thơ',
                'quang_duong' => 165.00,
                'cac_ngay_trong_tuan' => '[0,1,2,3,4,5,6]',
                'gio_khoi_hanh' => '08:00:00',
                'gio_ket_thuc' => '11:30:00',
                'gio_du_kien' => 4,
                'gia_ve_co_ban' => 165000.00,
                'id_xe' => 1,
                'ghi_chu' => 'Tuyến cao tốc TP.HCM - Trung Lương đi thủ phủ Miền Tây',
                'ghi_chu_admin' => null,
                'tinh_trang' => 'hoat_dong',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        // Thay 'tuyen_duongs' bằng tên bảng thực tế của bạn trong database
        DB::table('tuyen_duongs')->insert($routes);
    }
}
